
import {useState,useEffect} from 'react';
import {MapContainer,TileLayer,GeoJSON} from 'react-leaflet';
import {AreaChart,Area,BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts';
import 'leaflet/dist/leaflet.css';
import './App.css';
const GEO='https://raw.githubusercontent.com/wmgeolab/geoBoundaries/main/releaseData/gbOpen/BEN/ADM1/geoBoundaries-BEN-ADM1_simplified.geojson';
const DEPTS={Alibori:{score:78,meteo:'35C Ens.',incidents:12,trend:'up'},Atacora:{score:62,meteo:'31C Nua.',incidents:8,trend:'up'},Atlantique:{score:28,meteo:'30C Ens.',incidents:2,trend:'down'},Borgou:{score:55,meteo:'33C Ens.',incidents:6,trend:'stable'},Collines:{score:32,meteo:'32C Nua.',incidents:3,trend:'stable'},Couffo:{score:25,meteo:'29C Ens.',incidents:1,trend:'down'},Donga:{score:58,meteo:'30C Cou.',incidents:7,trend:'up'},Littoral:{score:20,meteo:'30C Ens.',incidents:1,trend:'down'},Mono:{score:22,meteo:'28C Ens.',incidents:2,trend:'stable'},Oueme:{score:30,meteo:'31C Ens.',incidents:3,trend:'stable'},Plateau:{score:35,meteo:'32C Nua.',incidents:3,trend:'stable'},Zou:{score:40,meteo:'31C Ens.',incidents:4,trend:'up'}};
const ALERTS=[{id:1,level:'CRITICAL',dept:'Alibori',msg:'Convergence: incidents+chaleur+frontiere',time:'09:47',active:true},{id:2,level:'HIGH',dept:'Atacora',msg:'Activite transfrontaliere inhabituelle',time:'08:23',active:true},{id:3,level:'MEDIUM',dept:'Borgou',msg:'Tensions communautaires zone pastorale',time:'07:15',active:false}];
const TICKER=['[SECURITE] Patrouilles renforcees zone Malanville-Karimama','[METEO] Alerte chaleur 42C prevus nord Benin','[DIPLO] Reunion CEDEAO Cotonou - agenda securitaire sous-region','[ECONOMIE] Hausse prix carburant +8% impact transport nord','[SECURITE] Incident frontalier Atacora - situation sous controle','[SANTE] Campagne vaccination meningite A departement Alibori','[POLITIQUE] Session parlement - budget defense en discussion'];
const CHART=[{m:'Jan',i:8,p:2.1},{m:'Fev',i:11,p:2.3},{m:'Mar',i:9,p:2.2},{m:'Avr',i:14,p:2.4},{m:'Mai',i:18,p:2.3},{m:'Jun',i:22,p:2.5},{m:'Jul',i:28,p:2.2},{m:'Aou',i:31,p:2.1},{m:'Sep',i:35,p:2.0},{m:'Oct',i:29,p:2.2},{m:'Nov',i:24,p:2.4},{m:'Dec',i:19,p:2.6}];
function riskColor(s){return s>70?'#ff2020':s>50?'#ff8800':s>30?'#ffdd00':'#22ff88';}
export default function App(){const [geo,setGeo]=useState(null);const [tick,setTick]=useState(0);const [time,setTime]=useState(new Date().toLocaleTimeString('fr-FR'));const [scores,setScores]=useState(DEPTS);const [sel,setSel]=useState(null);
useEffect(()=>{fetch(GEO).then(r=>r.json()).then(setGeo)},[]);
useEffect(()=>{const iv=setInterval(()=>{setTick(t=>t+1);setTime(new Date().toLocaleTimeString('fr-FR'));setScores(prev=>{const n={...prev};Object.keys(n).forEach(k=>{n[k]={...n[k],score:Math.max(0,Math.min(100,n[k].score+(Math.random()-0.48)*2))};});return n;});},30000);return ()=>clearInterval(iv);},[]);
const gS=Math.round(Object.values(scores).reduce((a,d)=>a+d.score,0)/Object.keys(scores).length);
const styleGeo=(f)=>{const nm=f.properties.shapeName||'';const d=scores[nm]||{score:30};return{weight:1,color:'#00ffcc33',fillColor:riskColor(d.score),fillOpacity:0.55};};
return(<div className='app'><header className='hdr'><div className='hdr-l'><span className='logo'>BJ MONITOR</span><span className='ver'>V6.0 DYNAMIC</span></div><div className='hdr-c'><span className='clk'>{time}</span><span className='gidx' style={{color:riskColor(gS)}}>INDICE NATIONAL: {gS}/100</span></div><div className='hdr-r'><span className='live'>DIRECT</span><span className='cyc'>Cycle {tick}</span></div></header>
<div className='body'><aside className='lpanel'><div className='pblk'><h3>COUCHES</h3><div className='layers'><div className='layer on'>SECURITE</div><div className='layer on'>METEO</div><div className='layer on'>ECONOMIE</div><div className='layer on'>FRONTIERES</div><div className='layer off'>INFRA</div></div></div>
<div className='pblk'><h3>INDICE PAR DEPT</h3>{Object.entries(scores).map(([k,v])=>(<div key={k} className='drow' onClick={()=>setSel(sel===k?null:k)}><span className='dnm'>{k}</span><div className='dbar'><div style={{width:Math.round(v.score)+'%',height:'100%',background:riskColor(v.score),transition:'width 0.5s'}}></div></div><span style={{color:riskColor(v.score),fontSize:'11px'}}>{Math.round(v.score)}</span></div>))}</div></aside>
<main className='mapa'><MapContainer center={[9.3,2.3]} zoom={7} style={{height:'100%',width:'100%'}} zoomControl={true}><TileLayer url='https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png' attribution='CartoDB'/>{geo&&<GeoJSON data={geo} style={styleGeo} onEachFeature={(f,l)=>{const nm=f.properties.shapeName||'?';const d=scores[nm]||{score:0,incidents:0,meteo:'N/A'};l.bindPopup('<b>'+nm+'</b><br>Risque: '+Math.round(d.score)+'/100<br>Incidents: '+d.incidents+'<br>Meteo: '+d.meteo);l.on('click',()=>setSel(nm));}}/>}</MapContainer></main>
<aside className='rpanel'><div className='pblk'><h3>ALERTES CONVERGENTES</h3>{ALERTS.map(a=>(<div key={a.id} className={'aitem '+(a.active?'aon':'aoff')}><span className={'alv '+a.level}>{a.level}</span><span className='adp'>{a.dept}</span><p className='amsg'>{a.msg}</p><span className='atm'>{a.time}</span></div>))}</div>
<div className='pblk'><h3>INCIDENTS (12 MOIS)</h3><ResponsiveContainer width='100%' height={120}><AreaChart data={CHART}><XAxis dataKey='m' tick={{fill:'#888',fontSize:9}}/><YAxis tick={{fill:'#888',fontSize:9}}/><Tooltip contentStyle={{background:'#111',border:'1px solid #00ffcc',fontSize:10}}/><Area type='monotone' dataKey='i' stroke='#ff4444' fill='#ff444433'/></AreaChart></ResponsiveContainer></div>
<div className='pblk'><h3>PIB CROISSANCE (%)</h3><ResponsiveContainer width='100%' height={100}><BarChart data={CHART}><XAxis dataKey='m' tick={{fill:'#888',fontSize:9}}/><Tooltip contentStyle={{background:'#111',border:'1px solid #00ffcc',fontSize:10}}/><Bar dataKey='p' fill='#00ccff66' stroke='#00ccff'/></BarChart></ResponsiveContainer></div>
{sel&&scores[sel]&&<div className='pblk detail'><h3>DEPARTEMENT: {sel}</h3><p>Score risque: <b style={{color:riskColor(scores[sel].score)}}>{Math.round(scores[sel].score)}/100</b></p><p>Incidents: {scores[sel].incidents}</p><p>Meteo: {scores[sel].meteo}</p><p>Tendance: {scores[sel].trend}</p></div>}</aside></div>
<footer className='ticker'><div className='tw'><div className='tc'>{[...TICKER,...TICKER].map((m,i)=>(<span key={i} className='tm'>{m} &nbsp;&nbsp;&#9654;&nbsp;&nbsp;</span>))}</div></div></footer></div>);}
